#!/bin/bash
#Функция для отображения справки
show help()
{
  echo "Использование: $0 [опции]"
  echo ""
  echo "Опции:"
  echo "  -u, --users     Вывести список пользователей и их домашнихдиректорий"
  echo "  -p, --processes   Вывести список запущенных процессов"
  echo "  -h, --help      Показать эту справку"
  echo "  -l PATH, --log PATH   Запись вывод в файл по заданному пути"
  echo "  -e PATH, --errors PATH   Запись ошибки в файл по заданному пути"
}

#Функция для вывода пользователей
list_users() {
  getent passwd | awk -F: '{print $1, $6}' | sort 
}
#Функция для вывода процессов
list_processes() {
  ps -eo pid,comm --sort=pid
}
#Основная функция
main() {

